import CI2ZF.Coupling.Foundations.TwoMetric
import CI2ZF.Potts.Model.Real.ActiveConstraints
import CI2ZF.Potts.Model.Real.SoftKernel
import CI2ZF.Potts.Model.Real.Endpoint
import CI2ZF.Analysis.PaperComplexAverage
import CI2ZF.Coupling.Foundations.ShellMarginals
import CI2ZF.Potts.Transfer.PottsAnalytic
import CI2ZF.Potts.Transfer.FixedGraph
import CI2ZF.Coupling.Vigoda.RootCI
import CI2ZF.Coupling.Vigoda.VigodaChargeFormula
import CI2ZF.Coupling.Vigoda.IncidenceMatching
import CI2ZF.Coupling.Vigoda.HardMatchCost
import CI2ZF.Coupling.Vigoda.HardFlipTotal
import CI2ZF.Coupling.Vigoda.ActiveDegree
import CI2ZF.Coupling.Vigoda.HardChargeSum
import CI2ZF.Coupling.Vigoda.HardRootColourSeparation
import CI2ZF.Coupling.Vigoda.HardPieceSums
import CI2ZF.Coupling.Vigoda.HardSingletonRegular
import CI2ZF.Coupling.Vigoda.HardGlobalCost
import CI2ZF.Potts.Transfer.SeparatorResponse
import CI2ZF.Potts.Geometry.SeparatorExterior
import CI2ZF.Coupling.Vigoda.PottsCITheorem
import CI2ZF.Coupling.Vigoda.ActivationCharge
import CI2ZF.Potts.Transfer.BoundedLocalFamily
import CI2ZF.Potts.Model.RootGibbsSemantics
import CI2ZF.Analysis.AnalyticComplexAverage
import CI2ZF.Potts.Transfer.PositiveParent
import CI2ZF.Potts.Transfer.HardParent
import CI2ZF.Potts.Transfer.HardAnalyticAverage
import CI2ZF.Potts.Transfer.SeparatorHardResponse
import CI2ZF.Potts.Transfer.ExteriorAnalyticResponses
import CI2ZF.Potts.Geometry.RootComponentFactorization
import CI2ZF.Potts.Geometry.BFSShellMarginals
import CI2ZF.Coupling.Vigoda.OptionCI
import CI2ZF.Potts.Transfer.LocalResponseLog
import CI2ZF.Potts.Model.OptionPartition
import CI2ZF.Potts.Transfer.SeparatorHardAnchor
import CI2ZF.Potts.Geometry.OptionShellMarginals
import CI2ZF.Potts.Transfer.HardSeparatorStep
import CI2ZF.Potts.Theorems.PottsMainTheorem
import CI2ZF.Potts.Theorems.PottsExternalTheorem
import CI2ZF.Potts.Theorems.GraphClassPottsTransfer
import CI2ZF.Coupling.Vigoda.PositiveExactCI
import CI2ZF.Potts.Transfer.PositiveFamilyTransfer
import CI2ZF.Potts.Theorems.PositiveGraphClassTransfer
import CI2ZF.Potts.Geometry.PinningLeafGirth
import CI2ZF.Coupling.Foundations.StationaryComparison
import CI2ZF.Potts.Model.Real.EndpointClosure
import CI2ZF.Coupling.Vigoda.CoupledActivation
import CI2ZF.Coupling.Vigoda.SoftFlipKernel
import CI2ZF.Coupling.Vigoda.RegularColourTable
import CI2ZF.Potts.Model.PinnedMarginal
import CI2ZF.Potts.Theorems.ThresholdComparison
import CI2ZF.Potts.Theorems.UniformClassConstants
import CI2ZF.Potts.Geometry.PinningLeafTransfer

/-! Main-text Potts coupling and zero-free theorems. -/
